services:
  openloc-frontend:
    build:
      context: .
      args:
        - VITE_API_BASE=https://openloc-backend.pichuka.net/api
        - VITE_WS_BASE=wss://openloc-backend.pichuka.net/ws
    ports:
      - "1234:80"
    restart: unless-stopped
